//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impamb.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstudiosImpactoAmbiental : DbContext
    {
        public EstudiosImpactoAmbiental()
            : base("name=EstudiosImpactoAmbiental")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TM_ESTUDIOS_IMPAMB> TM_ESTUDIOS_IMPAMB { get; set; }
        public DbSet<TC_UNIDAD_ADMINISTRATIVA> TC_UNIDAD_ADMINISTRATIVA { get; set; }
        public DbSet<TC_INSTRUMENTOS> TC_INSTRUMENTOS { get; set; }
    }
}
