//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impamb.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_INSTRUMENTOS
    {
        public string ESTATUS { get; set; }
        public string DESCRIPCION { get; set; }
        public string INICIALES { get; set; }
        public string USUARIO_INGRESO { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public string USUARIO_ACTUALIZACION { get; set; }
        public System.DateTime FECHA_ACTUALIZACION { get; set; }
    }
}
