//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Impamb.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_ESTUDIOS_IMPAMB
    {
        public short PERIODO { get; set; }
        public string NUMERO_ESTUDIO { get; set; }
        public string NOMBRE_PROYECTO { get; set; }
        public string REPRESENTANTE_LEGAL { get; set; }
        public string DIRECCION_PROYECTO { get; set; }
        public string TELEFONO { get; set; }
        public System.DateTime FECHA_CAPTURA { get; set; }
        public string NOMBRE_EMPRESA { get; set; }
        public string OBJETIVO_EMPRESA { get; set; }
        public string NOMBRE_CONSULTOR { get; set; }
        public string NIT_CONSULTOR { get; set; }
        public string ESTATUS_ESTUDIO { get; set; }
        public string ASESOR_DELEGACION { get; set; }
        public Nullable<System.DateTime> FECHA_RESOLUCION { get; set; }
        public string NUMERO_RESOLUCION { get; set; }
        public string ESTATUS_RESOLUCION { get; set; }
        public Nullable<System.DateTime> FECHA_NOTIFICACION { get; set; }
        public Nullable<int> NO_FOLIOS { get; set; }
        public Nullable<int> NO_ESTANTERIA { get; set; }
        public Nullable<int> NO_FILA { get; set; }
        public string ESTATUS { get; set; }
        public string USUARIO_INGRESO { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public string USUARIO_ACTUALIZACION { get; set; }
        public System.DateTime FECHA_ACTUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHA_ASESOR { get; set; }
        public string NUMERO_DICTAMEN { get; set; }
        public Nullable<System.DateTime> FECHA_DICTAMEN { get; set; }
        public string E_MAIL { get; set; }
        public string SOLICITA_AMPLIACION { get; set; }
        public string DIRECCION_NOTIFICACION { get; set; }
        public string DEPARTAMENTO { get; set; }
        public Nullable<int> UBICACION_GEOGRAFICA { get; set; }
        public Nullable<short> CODIGO_ENTIDAD { get; set; }
        public string TIPO { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<decimal> MONTO_INVERSION { get; set; }
        public string NIT_EMPRESA { get; set; }
        public string NO_CEDULA { get; set; }
        public Nullable<System.DateTime> FECHA_AVISO_PUBLICO { get; set; }
        public Nullable<System.DateTime> FECHA_VAVISO_PUBLICO { get; set; }
        public Nullable<short> NUMERO_EMPLEOS { get; set; }
        public string SECTOR { get; set; }
        public Nullable<decimal> LONGITUD_UTM { get; set; }
        public Nullable<decimal> LATITUD_UTM { get; set; }
        public Nullable<short> LONGITUD_GCG { get; set; }
        public Nullable<short> LONGITUD_MCG { get; set; }
        public Nullable<decimal> LONGITUD_SCG { get; set; }
        public Nullable<short> LATITUD_GCG { get; set; }
        public Nullable<short> LATITUD_MCG { get; set; }
        public Nullable<decimal> LATITUD_SCG { get; set; }
        public string LOCALIZACION_X_GC { get; set; }
        public string LOCALIZACION_Y_GC { get; set; }
        public string ESTATUS_ESTUDIO_RESOLUCION { get; set; }
        public string FUENTE { get; set; }
        public string CTAXATIVA { get; set; }
        public Nullable<System.DateTime> FECHA_RECIBIDO_NOTIFICACION { get; set; }
        public Nullable<int> CODIGO_MUNICIPIO { get; set; }
        public string CONCLUSION { get; set; }
        public Nullable<int> NUMERO_LICENCIA { get; set; }
        public string VISTA_PUBLICO { get; set; }
        public string RECTRA { get; set; }
        public string RESUELTO { get; set; }
        public string DPI { get; set; }
        public string INVERSION { get; set; }
        public Nullable<int> COD_DELEG_INGRESO { get; set; }
        public Nullable<short> CAUSALNOAPROBATORIO { get; set; }
        public Nullable<decimal> COD_DEPARTAMENTO { get; set; }
    }
}
